apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: registry-cluster-org
  namespace: registry
spec:
  secretName: registry-cluster-org
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: registry.cluster.org
  dnsNames:
  - registry.cluster.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - registry.cluster.org
