- hosts: master
  become: yes
  tasks:
   - name: copy registry certificate directory
     become_user: ubuntu
     copy:
       src: certificate
       dest: ~/
   - name: install letsencrypt
     shell: kubectl create -f ~/certificate/letsencrypt.yml >> letsencrypt_installed.txt
     become_user: ubuntu
     args:
       chdir: $HOME
       creates: letsencrypt_installed.txt
   - name: add certificate
     shell: kubectl create -f ~/certificate/certificate.yml >> cert_added.txt
     become_user: ubuntu
     args:
       chdir: $HOME
       creates: cert_added.txt
