apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config-docker
  namespace: registry
data:
  config.yml: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      s3:
        region: digitalocean-ams3
        regionendpoint: ams3.digitaloceanspaces.com
        bucket: bucket-name
        accesskey: access-key
        secretkey: secret-key
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
