- hosts: master
  become: yes
  become_user: root
  tasks:
    - name: Creating monitoring namespace
      shell: kubectl create namespace monitoring >> ~/monitoring_namespace_created.txt
      become_user: ubuntu
      args:
        chdir: $HOME
        creates: monitoring_namespace_created.txt
    - name: Making infrastructure directory in gluster storage
      file:
        path: /mnt/shared-directory/infrastructure
        state: directory
        mode: 0777
    - name: Making grafana directory in gluster storage
      file:
        path: /mnt/shared-directory/infrastructure/grafana
        state: directory
        mode: 0777
    - name: Making prometheus directory in gluster storage
      file:
        path: /mnt/shared-directory/infrastructure/prometheus
        state: directory
        mode: 0777
    - name: Making alertmanager directory in gluster storage
      file:
        path: /mnt/shared-directory/infrastructure/alertmanager
        state: directory
        mode: 0777
    - name: Copying PV and PVC to installation directory
      become_user: ubuntu
      copy:
        src: monitoring
        dest: ~/
    - name: Creating alertmanager persistent volume
      become_user: ubuntu
      shell: kubectl create -f ~/monitoring/alertmanager-volume.yaml >> alertmanager-volume_created.txt
      args:
        chdir: $HOME
        creates: alertmanager-volume_created.txt
    - name: Creating prometheus persistent volume
      become_user: ubuntu
      shell: kubectl create -f ~/monitoring/prometheus-volume.yaml >> prometheus-volume_created.txt
      args:
        chdir: $HOME
        creates: prometheus-volume_created.txt
    - name: Creating grafana persistent volume
      become_user: ubuntu
      shell: kubectl create -f ~/monitoring/grafana-volume.yaml >> grafana-volume_created.txt
      args:
        chdir: $HOME
        creates: grafana-volume_created.txt
    - name: Installing prometheus using HELM and Charts
      become_user: ubuntu
      shell: helm install -f /home/ubuntu/monitoring/prometheus.yaml stable/prometheus --namespace monitoring --name monitoring >> prometheus_installed.txt
      args:
        chdir: $HOME
        creates: prometheus_installed.txt
    - name: Installing grafana using HELM and Charts
      become_user: ubuntu
      shell: helm install -f /home/ubuntu/monitoring/grafana.yaml stable/grafana --namespace monitoring --name grafana >> grafana_installed.txt
      args:
        chdir: $HOME
        creates: grafana_installed.txt
