kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-volume
  labels:
    type: local
    namespace_name: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/shared-directory/infrastructure/prometheus"
