kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-volume
  labels:
    type: local
    namespace_name: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/shared-directory/infrastructure/prometheus"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-claim
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  selector:
    matchLabels:
      namespace_name: monitoring
