apiVersion: v1
kind: Secret
metadata:
  namespace: velero
  name: cloud-credentials
stringData:
  cloud: |
    [default]
    aws_access_key_id = ACCESS_KEY_HERE
    aws_secret_access_key = SECRET_ACCESS_KEY_HERE