apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-backup
  namespace: velero
spec:
  schedule: 0 1 * * *
  template:
    excludedNamespaces: null
    excludedResources: null
    hooks:
      resources: null
    includeClusterResources: null
    includedNamespaces:
    - '*'
    includedResources: null
    labelSelector: null
    storageLocation: ""
    ttl: 720h0m0s
    volumeSnapshotLocations: null