apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: monitoring-roozameh-org
  namespace: monitoring
spec:
  secretName: monitoring-roozameh-org
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: monitoring.roozameh.org
  dnsNames:
  - monitoring.roozameh.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - monitoring.roozameh.org
