apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: prometheus-roozameh-org
  namespace: monitoring
spec:
  secretName: prometheus-roozameh-org
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: prometheus.roozameh.org
  dnsNames:
  - prometheus.roozameh.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - prometheus.roozameh.org
